import Head from 'next/head'
import Header from '@/components/Header'
import Main from '@/components/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>To-Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/todo.svg" />
      </Head>
      <Header />
      <Main />
    </>
  )
}
